services:

  pacs-api:
    build:
      context: ./backend
      dockerfile: PACS.API/Dockerfile
    container_name: pacs-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Points to your local SQL Server on the host machine
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1434;Database=PACSDB;User Id=sa;Password=Aftab@3234;TrustServerCertificate=True;
      - Orthanc__Url=http://orthanc:8042
      - Orthanc__Username=orthanc
      - Orthanc__Password=orthanc
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pacs-network
    restart: unless-stopped

  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: pacs-orthanc
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc/webhook.lua:/etc/orthanc/webhook.lua:ro
      - orthanc-data:/var/lib/orthanc/db
      - orthanc-cache:/var/lib/orthanc/cache
    networks:
      - pacs-network
    depends_on:
      - pacs-api

  pacs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://192.168.1.34:5000/api
        - VITE_ORTHANC_URL=http://192.168.1.34:8042
    container_name: pacs-frontend
    ports:
      - "3000:80"
    networks:
      - pacs-network
    depends_on:
      - pacs-api

volumes:
  orthanc-data:
  orthanc-cache:

networks:
  pacs-network:
    driver: bridge
